version: '3.1'

services:

  mysqldbHomework:
    image: mysql:latest
    container_name: dbmysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=appNetology
      - MYSQL_USER=fostas
      - MYSQL_PASSWORD=pAss2345$
    volumes:
      - ./dump.sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always